### ISSUE TITLE
Consider Delivery Platform

### ISSUE THREAD

**Issue by sbryant-developer** [Team-Outbreak/item-finder#8]
# Options Include:
- Website/Web app
  - Requires domain registration?
- Mobile App
  - Too light-weight?
- Hybrid App

# To Consider:
- The main purpose is for on-the-go use, so the solution needs to be mobile-focused
- Internet connectivity may be sparse when searches are made (many stores have poor signals)

**Comment by garrettbryant** [comment]
If we want the app to work offline then that is something that we should consider early on, so that clients can cache results and update when connection is available.

Our current setup makes it easy to create a responsive website that we can aim to design mobile first.  I think that would be the best approach for now, and maybe developing a native/hybrid app can come later?

**Comment by sbryant-developer** [comment]
> if we want the app to work offline

I think we do want this. I know for me, literally every store around me has little-to-no service inside. That makes me think it's common.
✔️ **We can add a separate issue to add caching.**


> Developing a native/hybrid app later

I support that. The only catch there is that it'll cost money to register a domain. But maybe that's a fine overhead for now?
✔️ **We can add a new issue for domain research & registration.**

**Comment by sbryant-developer** [comment]
Added #9 and #10. Closing this issue.
